---
title: "UFPR: Análise de Séries Temporais - Lista 01"
author: "Luiz Paulo Tavares"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  latex_engine: xelatex
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1) Defina variável aleatória, processo estocástico e série temporal.

Formalmente, uma **variável aleatória** $X$ é uma função que mapeia o espaço amostral $\Omega$ de um experimento aleatório para o conjunto dos números reais $\mathbb{R}$, ou seja, $X: \Omega \to \mathbb{R}$. Para cada resultado $\omega \in \Omega$, a variável $X$ associa um valor real $X(\omega)$. De forma mais simples, uma variável aleatória é uma função que associa um número real a cada resultado. Por outro lado, **processo estocástico** representa uma coleção de variáveis aleatórias ${X(t)_{t \in T}}$ indexados para um conjunto $T$. Por fim, série temporal é um sequência de observações de uma variável $Y_{t}$ ao longo do tempo $t$. Em outras palavras: uma **série temporal** é uma coleção de valores ${Yt_{t \in T}}$, onde cada $Y_{t}$ é uma realização da variável aleatória $Y$ no tempo $t$

# 2) Defina processo estocástico ergódico e processo estocástico estacionário ( no sentido amplo (fraco) e no sentido estrito (forte)).

Um processo estocástico é ergódico se, e somente se, as propriedades estatísticas (a média, por exemplo) do processo podem ser inferidas a partir de uma realização ao longo do tempo. Ou seja, processo ergódico tem relação com o tamanho da amostra, i.e, com a representatividade amostral. 

# 3) Qual a diferença entre correlação serial e correlação simples? Exemplifique.

A diferença é a estrutural temporal presente em ambas as correlaçẽs. Na correlação simples, como na correlação de Pearson, há o cálculo de uma simples associação linear entre as variáveis; por outro lado, na correlação serial (autocorrelação), há a correlação entre as observações da série temporal. 

Formalmente temos que a correlação de Pearson é dada como segue: 

$$
\rho_{X,Y} = \frac{\sum_{i=1}^{n} (X_i - \bar{X})(Y_i - \bar{Y})}{\sqrt{\sum_{i=1}^{n} (X_i - \bar{X})^2} \sqrt{\sum_{i=1}^{n} (Y_i - \bar{Y})^2}}
$$
enquanto a autocorrelação: 

$$
\text{ACF}(k) = \frac{\sum_{i=1}^{n-k} (X_i - \bar{X})(X_{i+k} - \bar{X})}{\sum_{i=1}^{n} (X_i - \bar{X})^2}
$$

